name: Deploy Frontend to ECS

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build React App
        run: |
          cd applicantratingfrontend
          echo "REACT_APP_API_BASE_URL=http://candidatebackend-1759328448.us-west-1.elb.amazonaws.com/" > .env.production
          npm install
          npm run build

      - name: Build, Tag, Push Frontend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: candidateratingfrontend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG -f applicantratingfrontend/Dockerfile.frontend applicantratingfrontend
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Render New Task Definition
        id: taskdef
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: frontend-taskdef.json
          container-name: candidateratingfrontendcontainer
          image: ${{ steps.login-ecr.outputs.registry }}/candidateratingfrontend:latest

      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: candidateratingfrontendendtaskdef-service-rc19tdtx
          cluster: candidateratingbackend
